app:
  Port: 8080
  Host: localhost
  JwtSecret: "JwtSecret"
  Release: false
  RunMode: debug

mysql:
  address: 127.0.0.1:3307
  user: user     # 你本地 mysql 的用户名
  password: password # 你本地的 mysql 用户密码
  dbName: tiktok # 这里是你在 mysql 建立的数据库名称
  maxIdle: 20
  maxOpen: 20
  maxLifetime: 100
redis:
  host: 127.0.0.1:6379
  password:
  maxIdle: 20
  maxActive: 20
  idleTimeOut: 100